//! Data-driven tag rule engine for generating tags from metadata.
//!
//! Rules are defined as data (struct), not code (trait). Each rule is a
//! pure function that maps metadata items → tag candidates. New rules
//! are added by appending to the `default_rules()` array.

use super::registry::MetadataItem;

/// A tag candidate generated by a rule.
#[derive(Debug, Clone)]
pub struct TagCandidate {
    pub tag_name: String,
    pub tag_type: String,
}

/// How to transform extracted metadata values into a tag value.
pub enum TagValue {
    /// Template replacement: `{0}`, `{1}` etc. are replaced with key values.
    Pattern(&'static str),
    /// Custom pure function that transforms extracted values.
    Compute(fn(&[&str]) -> String),
}

/// A single tag rule — pure data, no behaviour.
pub struct TagRule {
    /// Tag name prefix, e.g. "camera" → "camera:Canon". Empty = no prefix.
    pub prefix: &'static str,
    /// Metadata keys to extract values for.
    pub keys: &'static [&'static str],
    /// How to transform values into the tag value.
    pub value: TagValue,
    /// Only apply when file_type matches (e.g. Some("jpeg")). None = any type.
    pub if_file_type: Option<&'static str>,
}

/// Evaluate a single rule against the given metadata.
pub fn evaluate_rule(
    rule: &TagRule,
    metadata: &[MetadataItem],
    file_type: &str,
) -> Option<TagCandidate> {
    if let Some(ft) = rule.if_file_type {
        if file_type != ft {
            return None;
        }
    }
    let values: Vec<&str> = rule
        .keys
        .iter()
        .filter_map(|k| {
            metadata
                .iter()
                .find(|m| m.key == *k)
                .map(|m| m.value.as_str())
        })
        .collect();
    if values.len() != rule.keys.len() {
        return None;
    }
    let tag_value = match &rule.value {
        TagValue::Pattern(p) => {
            let mut s = p.to_string();
            for (i, v) in values.iter().enumerate() {
                // EXIF display_value() wraps ASCII strings in quotes,
                // strip them for clean tag names
                let cleaned = v.trim_matches('"');
                s = s.replace(&format!("{{{i}}}"), cleaned);
            }
            s
        }
        TagValue::Compute(f) => f(&values),
    };
    let tag_name = if rule.prefix.is_empty() {
        tag_value
    } else {
        format!("{}:{}", rule.prefix, tag_value)
    };
    Some(TagCandidate {
        tag_name,
        tag_type: "auto".to_string(),
    })
}

/// Evaluate all rules against the given metadata.
pub fn evaluate_all(
    rules: &[TagRule],
    metadata: &[MetadataItem],
    file_type: &str,
) -> Vec<TagCandidate> {
    rules
        .iter()
        .filter_map(|r| evaluate_rule(r, metadata, file_type))
        .collect()
}

// ---------------------------------------------------------------------------
// Helper functions
// ---------------------------------------------------------------------------

pub fn parse_exposure_time(s: &str) -> f64 {
    if let Some(rest) = s.strip_prefix("1/") {
        rest.parse::<f64>().map(|d| 1.0 / d).unwrap_or(0.0)
    } else {
        s.parse::<f64>().unwrap_or(0.0)
    }
}

pub fn parse_dms(s: &str) -> f64 {
    let parts: Vec<&str> = s.split_whitespace().collect();
    if parts.len() >= 5 {
        let deg: f64 = parts.first().copied().unwrap_or("0").parse().unwrap_or(0.0);
        let min: f64 = parts.get(2).copied().unwrap_or("0").parse().unwrap_or(0.0);
        let sec: f64 = parts.get(4).copied().unwrap_or("0").parse().unwrap_or(0.0);
        deg + min / 60.0 + sec / 3600.0
    } else {
        s.parse().unwrap_or(0.0)
    }
}

pub fn gcd(a: u32, b: u32) -> u32 {
    if b == 0 {
        a
    } else {
        gcd(b, a % b)
    }
}

#[inline]
pub fn rule(
    prefix: &'static str,
    keys: &'static [&'static str],
    value: TagValue,
    if_file_type: Option<&'static str>,
) -> TagRule {
    TagRule {
        prefix,
        keys,
        value,
        if_file_type,
    }
}

impl TagRule {
    pub fn default_rules() -> Vec<Self> {
        use TagValue::*;
        vec![
            // ========== 基础文件类型分类 ==========
            rule("", &["file_type"], Pattern("image"), Some("jpeg")),
            rule("", &["file_type"], Pattern("image"), Some("png")),
            rule("", &["file_type"], Pattern("image"), Some("webp")),
            rule("", &["file_type"], Pattern("image"), Some("bmp")),
            rule("", &["file_type"], Pattern("image"), Some("tiff")),
            rule("", &["file_type"], Pattern("image"), Some("svg")),
            rule("", &["file_type"], Pattern("video"), Some("mp4")),
            rule("", &["file_type"], Pattern("video"), Some("mov")),
            rule("", &["file_type"], Pattern("video"), Some("avi")),
            rule("", &["file_type"], Pattern("video"), Some("mkv")),
            rule("", &["file_type"], Pattern("audio"), Some("mp3")),
            rule("", &["file_type"], Pattern("audio"), Some("flac")),
            rule("", &["file_type"], Pattern("audio"), Some("wav")),
            rule("", &["file_type"], Pattern("document"), Some("pdf")),
            rule("", &["file_type"], Pattern("document"), Some("doc")),
            rule("", &["file_type"], Pattern("document"), Some("docx")),
            // 相机信息
            rule("camera", &["Make"], Pattern("{0}"), None),
            rule("model", &["Model"], Pattern("{0}"), None),
            rule("lens", &["LensModel"], Pattern("{0}"), None),
            rule("lens_make", &["LensMake"], Pattern("{0}"), None),
            rule("owner", &["CameraOwnerName"], Pattern("{0}"), None),
            rule("serial", &["BodySerialNumber"], Pattern("{0}"), None),
            rule("software", &["Software"], Pattern("{0}"), None),
            rule("artist", &["Artist"], Pattern("{0}"), None),
            rule("copyright", &["Copyright"], Pattern("{0}"), None),
            // 拍摄参数（已离散）
            rule("program", &["ExposureProgram"], Pattern("{0}"), None),
            rule("exposure", &["ExposureMode"], Pattern("{0}"), None),
            rule("metering", &["MeteringMode"], Pattern("{0}"), None),
            rule("light", &["LightSource"], Pattern("{0}"), None),
            rule("whitebalance", &["WhiteBalance"], Pattern("{0}"), None),
            rule("scene", &["SceneCaptureType"], Pattern("{0}"), None),
            rule("colorspace", &["ColorSpace"], Pattern("{0}"), None),
            rule("contrast", &["Contrast"], Pattern("{0}"), None),
            rule("saturation", &["Saturation"], Pattern("{0}"), None),
            rule("sharpness", &["Sharpness"], Pattern("{0}"), None),
            rule("gain", &["GainControl"], Pattern("{0}"), None),
            rule("distance", &["SubjectDistanceRange"], Pattern("{0}"), None),
            rule("sensor", &["SensingMethod"], Pattern("{0}"), None),
            rule("source", &["FileSource"], Pattern("{0}"), None),
            rule("custom", &["CustomRendered"], Pattern("{0}"), None),
            rule("composite", &["CompositeImage"], Pattern("{0}"), None),
            // 连续→离散：焦距
            rule(
                "focal",
                &["FocalLengthIn35mmFilm"],
                Compute(|vals| {
                    let f: f64 = vals.first().copied().unwrap_or("0").parse().unwrap_or(0.0);
                    match f {
                        _ if f < 20.0 => "ultrawide",
                        _ if f < 35.0 => "wide",
                        _ if f < 70.0 => "normal",
                        _ if f < 200.0 => "tele",
                        _ => "supertele",
                    }
                    .to_string()
                }),
                None,
            ),
            rule(
                "focal",
                &["FocalLength"],
                Compute(|vals| {
                    let f: f64 = vals.first().copied().unwrap_or("0").parse().unwrap_or(0.0);
                    match f {
                        _ if f < 20.0 => "ultrawide",
                        _ if f < 35.0 => "wide",
                        _ if f < 70.0 => "normal",
                        _ if f < 200.0 => "tele",
                        _ => "supertele",
                    }
                    .to_string()
                }),
                None,
            ),
            // 连续→离散：光圈
            rule(
                "aperture",
                &["FNumber"],
                Compute(|vals| {
                    let f: f64 = vals.first().copied().unwrap_or("0").parse().unwrap_or(0.0);
                    match f {
                        _ if f <= 2.0 => "fast",
                        _ if f <= 2.8 => "bright",
                        _ if f <= 5.6 => "medium",
                        _ => "narrow",
                    }
                    .to_string()
                }),
                None,
            ),
            // 连续→离散：快门
            rule(
                "shutter",
                &["ExposureTime"],
                Compute(|vals| {
                    let t = parse_exposure_time(vals.first().copied().unwrap_or(""));
                    match t {
                        _ if t > 1.0 => "long",
                        _ if t > 1.0 / 30.0 => "slow",
                        _ if t > 1.0 / 250.0 => "normal",
                        _ if t > 1.0 / 4000.0 => "fast",
                        _ => "ultrafast",
                    }
                    .to_string()
                }),
                None,
            ),
            // 连续→离散：ISO
            rule(
                "iso",
                &["PhotographicSensitivity"],
                Compute(|vals| {
                    let iso: f64 = vals.first().copied().unwrap_or("0").parse().unwrap_or(0.0);
                    match iso {
                        _ if iso < 200.0 => "low",
                        _ if iso < 800.0 => "medium",
                        _ if iso < 6400.0 => "high",
                        _ => "extreme",
                    }
                    .to_string()
                }),
                None,
            ),
            // 连续→离散：曝光补偿
            rule(
                "exposure_bias",
                &["ExposureBiasValue"],
                Compute(|vals| {
                    let bias: f64 = vals.first().copied().unwrap_or("0").parse().unwrap_or(0.0);
                    match bias {
                        _ if bias < -0.5 => "negative",
                        _ if bias > 0.5 => "positive",
                        _ => "normal",
                    }
                    .to_string()
                }),
                None,
            ),
            // 连续→离散：亮度
            rule(
                "brightness",
                &["BrightnessValue"],
                Compute(|vals| {
                    let bv: f64 = vals.first().copied().unwrap_or("0").parse().unwrap_or(0.0);
                    match bv {
                        _ if bv < 0.0 => "dark",
                        _ if bv < 5.0 => "dim",
                        _ if bv < 10.0 => "normal",
                        _ => "bright",
                    }
                    .to_string()
                }),
                None,
            ),
            // 连续→离散：拍摄距离
            rule(
                "distance_m",
                &["SubjectDistance"],
                Compute(|vals| {
                    let d: f64 = vals.first().copied().unwrap_or("0").parse().unwrap_or(0.0);
                    match d {
                        _ if d < 0.3 => "macro",
                        _ if d < 3.0 => "near",
                        _ if d < 20.0 => "distant",
                        _ => "infinity",
                    }
                    .to_string()
                }),
                None,
            ),
            // 连续→离散：数码变焦
            rule(
                "digital_zoom",
                &["DigitalZoomRatio"],
                Compute(|vals| {
                    let z: f64 = vals.first().copied().unwrap_or("1").parse().unwrap_or(1.0);
                    match z {
                        _ if z <= 1.0 => "none",
                        _ if z <= 2.0 => "moderate",
                        _ => "heavy",
                    }
                    .to_string()
                }),
                None,
            ),
            // 连续→离散：宽高比
            rule(
                "aspect",
                &["PixelXDimension", "PixelYDimension"],
                Compute(|vals| {
                    let w: u32 = vals.first().copied().unwrap_or("1").parse().unwrap_or(1);
                    let h: u32 = vals.get(1).copied().unwrap_or("1").parse().unwrap_or(1);
                    let g = gcd(w, h);
                    format!("{}:{}", w / g, h / g)
                }),
                None,
            ),
            // 连续→离散：分辨率
            rule(
                "resolution",
                &["XResolution"],
                Compute(|vals| {
                    let dpi: f64 = vals.first().copied().unwrap_or("0").parse().unwrap_or(0.0);
                    match dpi {
                        _ if dpi < 150.0 => "draft",
                        _ if dpi < 300.0 => "standard",
                        _ => "high",
                    }
                    .to_string()
                }),
                None,
            ),
            // 时间维度
            rule(
                "date",
                &["DateTimeOriginal"],
                Compute(|vals| {
                    vals.first()
                        .copied()
                        .unwrap_or("")
                        .get(..10)
                        .unwrap_or("")
                        .to_string()
                }),
                None,
            ),
            rule(
                "year",
                &["DateTimeOriginal"],
                Compute(|vals| {
                    vals.first()
                        .copied()
                        .unwrap_or("")
                        .get(..4)
                        .unwrap_or("")
                        .to_string()
                }),
                None,
            ),
            rule(
                "month",
                &["DateTimeOriginal"],
                Compute(|vals| {
                    vals.first()
                        .copied()
                        .unwrap_or("")
                        .get(..7)
                        .unwrap_or("")
                        .to_string()
                }),
                None,
            ),
            rule(
                "season",
                &["DateTimeOriginal"],
                Compute(|vals| {
                    let m: u32 = vals
                        .first()
                        .copied()
                        .unwrap_or("")
                        .get(5..7)
                        .and_then(|s| s.parse().ok())
                        .unwrap_or(0);
                    match m {
                        3..=5 => "spring",
                        6..=8 => "summer",
                        9..=11 => "autumn",
                        _ => "winter",
                    }
                    .to_string()
                }),
                None,
            ),
            rule(
                "timeofday",
                &["DateTimeOriginal"],
                Compute(|vals| {
                    let h: u32 = vals
                        .first()
                        .copied()
                        .unwrap_or("")
                        .get(11..13)
                        .and_then(|s| s.parse().ok())
                        .unwrap_or(0);
                    match h {
                        4..=6 => "dawn",
                        7..=10 => "morning",
                        11..=12 => "midday",
                        13..=16 => "afternoon",
                        17..=19 => "dusk",
                        _ => "night",
                    }
                    .to_string()
                }),
                None,
            ),
            // 时区
            rule(
                "timezone",
                &["OffsetTimeOriginal"],
                Compute(|vals| {
                    let tz = vals.first().copied().unwrap_or("").trim_matches('"').trim();
                    // "+08:00" → "UTC+8", "-05:00" → "UTC-5"
                    if let Some(rest) = tz.strip_prefix("+") {
                        format!(
                            "UTC+{}",
                            rest.trim_end_matches(":00").trim_end_matches(":0")
                        )
                    } else if let Some(rest) = tz.strip_prefix("-") {
                        format!(
                            "UTC-{}",
                            rest.trim_end_matches(":00").trim_end_matches(":0")
                        )
                    } else {
                        tz.to_string()
                    }
                }),
                None,
            ),
            // 环境参数
            rule(
                "temperature",
                &["Temperature"],
                Compute(|vals| {
                    let t: f64 = vals.first().copied().unwrap_or("0").parse().unwrap_or(0.0);
                    match t {
                        _ if t < 5.0 => "cold",
                        _ if t < 20.0 => "mild",
                        _ if t < 30.0 => "warm",
                        _ => "hot",
                    }
                    .to_string()
                }),
                None,
            ),
            rule(
                "humidity",
                &["Humidity"],
                Compute(|vals| {
                    let h: f64 = vals
                        .first()
                        .copied()
                        .unwrap_or("50")
                        .parse()
                        .unwrap_or(50.0);
                    match h {
                        _ if h < 30.0 => "dry",
                        _ if h < 70.0 => "normal",
                        _ => "humid",
                    }
                    .to_string()
                }),
                None,
            ),
            rule(
                "pressure",
                &["Pressure"],
                Compute(|vals| {
                    let p: f64 = vals
                        .first()
                        .copied()
                        .unwrap_or("1013")
                        .parse()
                        .unwrap_or(1013.0);
                    match p {
                        _ if p < 1000.0 => "low",
                        _ if p < 1020.0 => "normal",
                        _ => "high",
                    }
                    .to_string()
                }),
                None,
            ),
            // GPS
            rule(
                "grid",
                &["GPSLatitude", "GPSLongitude"],
                Compute(|vals| {
                    let lat = parse_dms(vals.first().copied().unwrap_or(""));
                    let lon = parse_dms(vals.get(1).copied().unwrap_or(""));
                    format!(
                        "{:.2}_{:.2}",
                        (lat * 100.0).round() / 100.0,
                        (lon * 100.0).round() / 100.0
                    )
                }),
                None,
            ),
            rule(
                "altitude",
                &["GPSAltitude"],
                Compute(|vals| {
                    let a: f64 = vals.first().copied().unwrap_or("0").parse().unwrap_or(0.0);
                    match a {
                        _ if a < 50.0 => "sea_level",
                        _ if a < 500.0 => "low",
                        _ if a < 2000.0 => "medium",
                        _ => "high",
                    }
                    .to_string()
                }),
                None,
            ),
            rule(
                "direction",
                &["GPSImgDirection"],
                Compute(|vals| {
                    let d: f64 = vals.first().copied().unwrap_or("0").parse().unwrap_or(0.0);
                    let dirs = ["N", "NE", "E", "SE", "S", "SW", "W", "NW"];
                    dirs.get(((d / 45.0).round() as usize) % 8)
                        .copied()
                        .unwrap_or("N")
                        .to_string()
                }),
                None,
            ),
            rule(
                "speed",
                &["GPSSpeed"],
                Compute(|vals| {
                    let s: f64 = vals.first().copied().unwrap_or("0").parse().unwrap_or(0.0);
                    match s {
                        _ if s < 1.0 => "stationary",
                        _ if s < 6.0 => "walking",
                        _ if s < 15.0 => "running",
                        _ if s < 120.0 => "driving",
                        _ => "flying",
                    }
                    .to_string()
                }),
                None,
            ),
            rule(
                "gps_accuracy",
                &["GPSDOP"],
                Compute(|vals| {
                    let d: f64 = vals
                        .first()
                        .copied()
                        .unwrap_or("99")
                        .parse()
                        .unwrap_or(99.0);
                    match d {
                        _ if d < 2.0 => "excellent",
                        _ if d < 5.0 => "good",
                        _ if d < 10.0 => "moderate",
                        _ => "poor",
                    }
                    .to_string()
                }),
                None,
            ),
        ]
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::extractor::registry::MetadataItem;

    #[test]
    fn test_evaluate_rule_pattern() {
        let rule = TagRule {
            prefix: "camera",
            keys: &["Make"],
            value: TagValue::Pattern("{0}"),
            if_file_type: None,
        };
        let metadata = [MetadataItem {
            namespace: "exif",
            key: "Make".into(),
            value: "Canon".into(),
        }];
        let result = evaluate_rule(&rule, &metadata, "jpeg");
        assert!(result.is_some());
        assert_eq!(result.unwrap().tag_name, "camera:Canon");
    }

    #[test]
    fn test_evaluate_rule_compute() {
        let rule = TagRule {
            prefix: "aspect",
            keys: &["PixelXDimension", "PixelYDimension"],
            value: TagValue::Compute(|vals| {
                let w: u32 = vals[0].parse().unwrap();
                let h: u32 = vals[1].parse().unwrap();
                let g = gcd(w, h);
                format!("{}:{}", w / g, h / g)
            }),
            if_file_type: None,
        };
        let metadata = [
            MetadataItem {
                namespace: "exif",
                key: "PixelXDimension".into(),
                value: "1920".into(),
            },
            MetadataItem {
                namespace: "exif",
                key: "PixelYDimension".into(),
                value: "1080".into(),
            },
        ];
        let result = evaluate_rule(&rule, &metadata, "jpeg");
        assert!(result.is_some());
        assert_eq!(result.unwrap().tag_name, "aspect:16:9");
    }

    #[test]
    fn test_evaluate_rule_file_type_filter() {
        let rule = TagRule {
            prefix: "",
            keys: &["file_type"],
            value: TagValue::Pattern("image"),
            if_file_type: Some("jpeg"),
        };
        let metadata = [MetadataItem {
            namespace: "exif",
            key: "file_type".into(),
            value: "jpeg".into(),
        }];
        assert!(evaluate_rule(&rule, &metadata, "jpeg").is_some());
        assert!(evaluate_rule(&rule, &metadata, "mp4").is_none());
    }

    #[test]
    fn test_evaluate_rule_missing_key_returns_none() {
        let rule = TagRule {
            prefix: "camera",
            keys: &["Make"],
            value: TagValue::Pattern("{0}"),
            if_file_type: None,
        };
        let metadata = [];
        assert!(evaluate_rule(&rule, &metadata, "jpeg").is_none());
    }

    #[test]
    fn test_evaluate_all_returns_multiple_tags() {
        let rules = TagRule::default_rules();
        let metadata = [
            MetadataItem {
                namespace: "exif",
                key: "file_type".into(),
                value: "jpeg".into(),
            },
            MetadataItem {
                namespace: "exif",
                key: "Make".into(),
                value: "Canon".into(),
            },
            MetadataItem {
                namespace: "exif",
                key: "Model".into(),
                value: "EOS R5".into(),
            },
            MetadataItem {
                namespace: "exif",
                key: "PixelXDimension".into(),
                value: "1920".into(),
            },
            MetadataItem {
                namespace: "exif",
                key: "PixelYDimension".into(),
                value: "1080".into(),
            },
        ];
        let tags = evaluate_all(&rules, &metadata, "jpeg");
        assert!(tags.iter().any(|t| t.tag_name == "image"));
        assert!(tags.iter().any(|t| t.tag_name == "camera:Canon"));
        assert!(tags.iter().any(|t| t.tag_name == "model:EOS R5"));
        assert!(tags.iter().any(|t| t.tag_name == "aspect:16:9"));
    }

    #[test]
    fn test_parse_exposure_time() {
        assert!((parse_exposure_time("1/125") - 0.008).abs() < 0.001);
        assert!((parse_exposure_time("0.5") - 0.5).abs() < 0.001);
        assert!((parse_exposure_time("30") - 30.0).abs() < 0.001);
    }

    #[test]
    fn test_parse_dms() {
        let result = parse_dms("34 deg 42 min 12.5 sec");
        assert!((result - 34.70347).abs() < 0.001);
    }

    #[test]
    fn test_gcd() {
        assert_eq!(gcd(1920, 1080), 120);
        assert_eq!(gcd(16, 9), 1);
        assert_eq!(gcd(100, 1), 1);
    }
}
