[workspace]
resolver = "2"
members = [
    "crates/s3-gallery-core",
    "crates/s3-gallery-cli",
    "crates/s3-gallery-web",
]

[package]
name = "s3-gallery-tests"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
tempfile = "3"
tokio = { version = "1", features = ["full"] }
s3-gallery-core = { path = "crates/s3-gallery-core" }
uuid = { version = "1", features = ["v4"] }
aws-sdk-s3 = "1.138.1"
aws-config = "1.5.0"
sea-orm = { version = "1", features = ["sqlx-sqlite", "runtime-tokio-rustls"] }
sqlx = { version = "0.8", features = ["runtime-tokio", "sqlite"] }
async-trait = "0.1"