[package]
name = "ossgalley-cli"
edition = "2021"
version = "0.1.0"

[dependencies]
ossgalley-core = { path = "../ossgalley-core" }
clap = { version = "4", features = ["derive", "env"] }
tokio = { version = "1", features = ["full"] }
tracing-subscriber = "0.3"
chrono = "0.4"
uuid = { version = "1.0", features = ["v4"] }