[package]
name = "ossgalley-web"
edition = "2021"
version = "0.1.0"

[dependencies]
ossgalley-core = { path = "../ossgalley-core" }
axum = "0.7"
sqlx = { version = "0.8", features = ["runtime-tokio", "sqlite"] }
tokio = { version = "1", features = ["full"] }
tower-http = { version = "0.5", features = ["cors", "trace"] }
minijinja = "2"
serde = { version = "1", features = ["derive"] }
tracing = "0.1"
tracing-subscriber = "0.3"
serde_json = "1.0"